stages:
- build

build:
  stage: build
  image: maven:3.5.3-jdk-8
  script: "mvn clean package"
  artifacts:
    name: "UltimateKits"
    paths:
    - "/builds/Songoda/UltimateKits/target/*.jar"
    - "/builds/Songoda/UltimateKits/Read_this_before_your_first_use.txt"
