name: UltimateKits
main: com.songoda.ultimatekits.UltimateKits
version: maven-version-number
depend: [Arconix]
softdepend: [PlaceholderAPI, Vault, UltimateCore, Essentials, MiniKitPvP]
description: View a kit before you purchase it!
author: Songoda
api-version: 1.13
commands:
  kitadmin:
    description: View information on this plugin.
    default: true
    aliases: [ultimatekits, kp, uk]
    usage: /<command> [reload]
  kit:
    description: Preview a kit
    default: true
    aliases: [kits]
    usage: /<commands>
  previewkit:
    description: Preview a kit
    default: true
    aliases: [pk, preview]
    usage: /<command> [kit]
permissions:
  ultimatekits.use:
    description: allows the user to preview kit
    default: true
  ultimatekits.admin:
    description: Gives access to admin commands.